import type { Cell } from "./types";

export const TOTAL_CELLS = 72;
export const COLS = 9;
export const ROWS = 8;
export const GOAL_CELL = 68;

export const BOARD_CELLS: Cell[] = [
  { id: 1, name: "Народження", original: "Janma", description: "Початок шляху. Душа входить у гру життя." },
  { id: 2, name: "Майя", original: "Maya", description: "Ілюзія, що приховує справжню природу реальності." },
  { id: 3, name: "Гнів", original: "Krodha", description: "Вогонь, що спалює ясність розуму." },
  { id: 4, name: "Жадібність", original: "Lobha", description: "Прагнення володіти більшим, ніж потрібно." },
  { id: 5, name: "Фізичний план", original: "Bhu Loka", description: "Світ матерії та грубих форм." },
  { id: 6, name: "Омана", original: "Moha", description: "Затьмарення розуму прив'язаностями." },
  { id: 7, name: "Марнославство", original: "Mada", description: "Опьяніння власною важливістю." },
  { id: 8, name: "Скупість", original: "Matsara", description: "Страх віддати, що сковує душу." },
  { id: 9, name: "Чуттєвий план", original: "Kama Loka", description: "Світ бажань і чуттєвих насолод.", arrowTo: 31 },
  { id: 10, name: "Очищення", original: "Tapa Loka", description: "Внутрішній вогонь, що випалює нечистоту.", arrowTo: 23 },
  { id: 11, name: "Розваги", original: "Gandharva", description: "Привабливі форми, що відволікають від суті." },
  { id: 12, name: "Заздрість", original: "Irshya", description: "Біль від чужого щастя.", snakeTo: 8 },
  { id: 13, name: "Нікчемність", original: "Apatra", description: "Відчуття власної недостойності." },
  { id: 14, name: "Астральний план", original: "Bhuvar Loka", description: "Тонкий світ між матерією і духом." },
  { id: 15, name: "План фантазії", original: "Naga Loka", description: "Світ уяви та внутрішніх образів." },
  { id: 16, name: "Ревність", original: "Dwesha", description: "Бажання володіти тим, що не можна втримати.", snakeTo: 4 },
  { id: 17, name: "Співчуття", original: "Daya", description: "Серце, що відкривається болю іншого." },
  { id: 18, name: "План радості", original: "Yaksha Loka", description: "Світ легкої радості та внутрішньої гри." },
  { id: 19, name: "План карми", original: "Karma Loka", description: "Закон причини і наслідку у дії." },
  { id: 20, name: "Милосердя", original: "Dana", description: "Дар без очікування взаємності.", arrowTo: 32 },
  { id: 21, name: "Спокута", original: "Prayaschitta", description: "Очищення через визнання помилки." },
  { id: 22, name: "План дгарми", original: "Dharma Loka", description: "Слідування своєму істинному обов'язку.", arrowTo: 60 },
  { id: 23, name: "Небесний план", original: "Swarga Loka", description: "Винагорода за добрі справи; тимчасова насолода." },
  { id: 24, name: "Лихе товариство", original: "Kusangam", description: "Оточення, що тягне свідомість донизу.", snakeTo: 7 },
  { id: 25, name: "Добре товариство", original: "Sat-Sangam", description: "Присутність тих, хто пробуджує найкраще." },
  { id: 26, name: "Скорбота", original: "Dukha", description: "Біль як учитель внутрішньої глибини." },
  { id: 27, name: "Безкорисливе служіння", original: "Paropakara", description: "Дія заради інших як шлях до себе.", arrowTo: 41 },
  { id: 28, name: "Істинна релігійність", original: "Saguna", description: "Жива віра, не зведена до ритуалу.", arrowTo: 50 },
  { id: 29, name: "Відсутність релігійності", original: "Adharma", description: "Втрата зв'язку з вищим порядком.", snakeTo: 5 },
  { id: 30, name: "Добрі схильності", original: "Sat-Vasana", description: "Внутрішні насіння, що ведуть до світла." },
  { id: 31, name: "План святості", original: "Maharloka", description: "Чистота, що пронизує усі дії." },
  { id: 32, name: "План рівноваги", original: "Janaloka", description: "Спокій між протилежностями." },
  { id: 33, name: "План ароматів", original: "Gandha", description: "Тонкий світ, що сприймається нюхом духу." },
  { id: 34, name: "План смаку", original: "Rasa", description: "Світ, у якому відчуття стає поезією." },
  { id: 35, name: "Чистилище", original: "Naraka", description: "Простір, де згоряють залишки тіні." },
  { id: 36, name: "Ясність свідомості", original: "Suddha-Chitta", description: "Розум-дзеркало без брижів." },
  { id: 37, name: "Джняна", original: "Jnana", description: "Знання, що переживається безпосередньо.", arrowTo: 66 },
  { id: 38, name: "Прана-лока", original: "Prana-Loka", description: "Світ висхідного життєвого подиху." },
  { id: 39, name: "Апана-лока", original: "Apana-Loka", description: "Світ низхідної енергії очищення." },
  { id: 40, name: "В'яна-лока", original: "Vyana-Loka", description: "Енергія, що пронизує усе тіло." },
  { id: 41, name: "Людський план", original: "Manushya", description: "Дорогоцінне народження як шанс пробудитись." },
  { id: 42, name: "План Агні", original: "Agni Loka", description: "Очисний вогонь свідомості." },
  { id: 43, name: "Людське народження", original: "Manushya-Janma", description: "Втілення зі здатністю усвідомлювати себе." },
  { id: 44, name: "Невігластво", original: "Avidya", description: "Корінь страждання — незнання своєї природи.", snakeTo: 9 },
  { id: 45, name: "Правильне знання", original: "Vidya", description: "Бачення речей такими, якими вони є.", arrowTo: 67 },
  { id: 46, name: "Розрізнення", original: "Viveka", description: "Здатність відрізняти вічне від минущого.", arrowTo: 62 },
  { id: 47, name: "План нейтральності", original: "Saumya", description: "Внутрішня тиша поза реакціями." },
  { id: 48, name: "Сонячний план", original: "Surya Loka", description: "Ясність, що осяває все рівним світлом." },
  { id: 49, name: "Місячний план", original: "Chandra Loka", description: "М'яке сяйво інтуїції та спокою." },
  { id: 50, name: "План аскези", original: "Tapas", description: "Дисципліна, що загартовує дух." },
  { id: 51, name: "Земля", original: "Prithvi", description: "Опертя, з якого починається будь-яке сходження." },
  { id: 52, name: "План насильства", original: "Himsa", description: "Енергія, повернута проти життя.", snakeTo: 35 },
  { id: 53, name: "План рідин", original: "Jala", description: "Світ почуттів, що тече і змінюється." },
  { id: 54, name: "План духовної відданості", original: "Bhakti", description: "Любов, що сама стає шляхом.", arrowTo: 68 },
  { id: 55, name: "Егоїзм", original: "Ahamkara", description: "Я-вузол, що відокремлює від цілого.", snakeTo: 3 },
  { id: 56, name: "План первісних вібрацій", original: "Nada", description: "Звук, з якого виникає все." },
  { id: 57, name: "План газів", original: "Vayu Loka", description: "Світ тонкого руху і подиху." },
  { id: 58, name: "План сяйва", original: "Tejas", description: "Внутрішнє світло, що не має джерела." },
  { id: 59, name: "План реальності", original: "Satya Loka", description: "Те, що залишається, коли все інше зникає." },
  { id: 60, name: "Позитивний інтелект", original: "Su-Buddhi", description: "Розум, скерований до світла." },
  { id: 61, name: "Негативний інтелект", original: "Dur-Buddhi", description: "Розум, що служить тіні.", snakeTo: 13 },
  { id: 62, name: "Щастя", original: "Sukha", description: "Тиха повнота буття." },
  { id: 63, name: "Тамас", original: "Tamas", description: "Інерція, темрява, забуття.", snakeTo: 2 },
  { id: 64, name: "Феноменальний план", original: "Vishaya", description: "Світ форм, що з'являються і зникають." },
  { id: 65, name: "План внутрішнього простору", original: "Akasha", description: "Простір, у якому виникають усі переживання." },
  { id: 66, name: "План блаженства", original: "Ananda", description: "Радість, що не залежить від причин." },
  { id: 67, name: "План космічного добра", original: "Param-Shubha", description: "Добро, що дихає в основі світу." },
  { id: 68, name: "Космічна свідомість", original: "Brahma Loka", description: "Ціль гри: впізнавання своєї вічної природи." },
  { id: 69, name: "План Абсолюту", original: "Saguna Brahman", description: "Божественне з якостями, відчутне серцем." },
  { id: 70, name: "Саттва-Гуна", original: "Sattva", description: "Якість гармонії, чистоти і світла." },
  { id: 71, name: "Раджо-Гуна", original: "Rajas", description: "Якість руху, пристрасті, дії." },
  { id: 72, name: "Тамо-Гуна", original: "Tamas-Guna", description: "Якість спокою, що межує зі сном.", snakeTo: 51 },
];

export function getCell(id: number): Cell | undefined {
  return BOARD_CELLS.find((c) => c.id === id);
}
